# Generated by Django 2.1 on 2018-08-27 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Plataforma_web', '0003_auto_20180827_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phi', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Potential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('potential', models.IntegerField()),
                ('phi', models.FloatField()),
                ('temp', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
