# Generated by Django 2.1 on 2018-08-28 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Plataforma_web', '0004_dynamicmodule_potential'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamicmodule',
            name='id_user',
        ),
        migrations.RemoveField(
            model_name='potential',
            name='id_user',
        ),
        migrations.DeleteModel(
            name='DynamicModule',
        ),
        migrations.DeleteModel(
            name='Potential',
        ),
    ]
